export enum CollecKind
{
    User,
    StudentVerification,
    Group,
    GroupMember,
    Association,
    GroupHistory,
    GroupHistoryCmt,
    GroupHistoryLike,
    GroupQna,
    GroupSchedule,
    GroupBill,
    GroupVote,
    GroupNotice,
    ChatRoom,
    ChatMember,
    ChatMsg,
}
